### ISSUE TITLE
use of readOnly, writeOnly violates the spec (?) and usage with PUT etc

### ISSUE THREAD

**Issue by karenetheridge** [karenetheridge/OpenAPI-Modern#37]
I have implemented `readOnly` such that a property with that annotation cannot be used in requests (and similarly for `writeOnly` in responses). However, this prevents the labelling of a property as readOnly if it is to be used in a PUT, where (by REST convention) all properties are provided and the data overwrites the original idempotently -- here, the meaning is "this property may be present, but it can't change from its original value". As such it should only be treated as an annotation, and the application should figure out what to do with it, rather than generating a validation error itself.

Therefore:
- remove the checking of readOnly, writeOnly in validate_request and validate_response
- provide guidance (in cookbook documentation?) for getting these annotations out of the result and determining if the referenced properties are changing values.
- provide guidance for how to indicate that a particular propertly should not be present at all:

```
allOf:
  not:
    required: [id]
  not:
    required: [created]
  not:
    required: [updated]
```

or:

```
properties:
  id: false
  created: false
  updated: false
```

or:

```
$ref: '#/components/schemas/model.foo'
additionalProperties: false
properties:
  foo: true # property in model.foo
  bar: true # property in model.foo
  blah: true # property in model.foo
```
