### ISSUE TITLE
add x-delimiter for style/explode customization

### ISSUE THREAD

**Issue by karenetheridge** [karenetheridge/OpenAPI-Modern#64]
I would like to do this:

```yaml
components:
  headers:
    Surrogate-Key:
      description: see https://docs.fastly.com/en/guides/working-with-surrogate-keys
      style: simple  # default
      explode: false # default
      x-delimiter: ' '
      schema:
        type: array
        items:
          type: string
          pattern: ^myapp-
```

..because this header is formatted as space-separated strings, rather than comma-separated.
